/**
 * Codex app-server realtime protocol.
 *
 * The notification shapes are generated by `codex app-server generate-ts`, but
 * the six request methods are gated out of those bindings even with the feature
 * flag on, so they are written by hand here from the method table in the codex
 * binary. Verified against codex-cli 0.149.1.
 */

export type RealtimeVoice =
  | "alloy" | "arbor" | "ash" | "ballad" | "breeze" | "cedar" | "coral"
  | "cove" | "echo" | "ember" | "juniper" | "maple" | "marin" | "sage"
  | "shimmer" | "sol" | "spruce" | "vale" | "verse";

export type RealtimeConversationVersion = "v1" | "v2" | "v3";
export type RealtimeTransport = "websocket" | "webrtc";

/** Self-describing audio payload. `data` is base64 PCM16. */
export interface ThreadRealtimeAudioChunk {
  data: string;
  sampleRate: number;
  numChannels: number;
  samplesPerChannel: number | null;
  itemId: string | null;
}

export interface RealtimeStartParams {
  threadId: string;
  transport: RealtimeTransport;
  voice?: RealtimeVoice;
  /** Spoken to the model when the session opens. */
  realtimeStartInstructions?: string;
  /** Spoken to the model when the session is torn down. */
  realtimeEndInstructions?: string;
  prompt?: string;
  /** WebRTC only: the local offer. Leave unset for websocket transport. */
  sdp?: string;
  realtimeSessionId?: string;
}

export interface RealtimeAppendAudioParams {
  threadId: string;
  audio: ThreadRealtimeAudioChunk;
}

export interface RealtimeAppendTextParams {
  threadId: string;
  text: string;
}

/** Make the agent speak this verbatim, bypassing the model. */
export interface RealtimeAppendSpeechParams {
  threadId: string;
  text: string;
}

export interface RealtimeStopParams {
  threadId: string;
}

export interface RealtimeVoicesList {
  voices: {
    v1: string[];
    v2: string[];
    defaultV1: string;
    defaultV2: string;
  };
}

export const REALTIME_METHODS = {
  start: "thread/realtime/start",
  appendAudio: "thread/realtime/appendAudio",
  appendText: "thread/realtime/appendText",
  appendSpeech: "thread/realtime/appendSpeech",
  stop: "thread/realtime/stop",
  listVoices: "thread/realtime/listVoices",
} as const;

/** Server notifications we care about. */
export const REALTIME_NOTIFICATIONS = {
  started: "thread/realtime/started",
  closed: "thread/realtime/closed",
  error: "thread/realtime/error",
  itemAdded: "thread/realtime/itemAdded",
  outputAudioDelta: "thread/realtime/outputAudio/delta",
  transcriptDelta: "thread/realtime/transcript/delta",
  transcriptDone: "thread/realtime/transcript/done",
  sdp: "thread/realtime/sdp",
} as const;

export interface ThreadRealtimeStartedNotification {
  threadId: string;
  realtimeSessionId: string | null;
  version: RealtimeConversationVersion;
}

export interface ThreadRealtimeOutputAudioDeltaNotification {
  threadId: string;
  audio: ThreadRealtimeAudioChunk;
}

export interface ThreadRealtimeTranscriptDeltaNotification {
  threadId: string;
  delta: string;
  role?: string;
}

export interface ThreadRealtimeTranscriptDoneNotification {
  threadId: string;
  text: string;
  role?: string;
}
